// Complete, battle-tested SQL script for Supabase Database & Storage for AlexStore
export const SUPABASE_SCHEMA_SQL = `-- ========================================================
-- ALEXSTORE - SCRIPT SQL COMPLETO PARA SUPABASE
-- Copia y pega este script en: Supabase Dashboard -> SQL Editor -> Run
-- ========================================================

-- 1. CONCEDER PERMISOS BÁSICOS EN EL ESQUEMA PUBLIC
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO anon, authenticated, service_role;

-- 2. TABLA DE PERFILES (Para administradores y usuarios)
CREATE TABLE IF NOT EXISTS public.perfiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  nombre TEXT,
  rol TEXT NOT NULL DEFAULT 'admin', -- Por defecto admin para el creador
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;

-- Políticas de perfiles
DROP POLICY IF EXISTS "Lectura de perfiles" ON public.perfiles;
CREATE POLICY "Lectura de perfiles" ON public.perfiles FOR SELECT TO public USING (TRUE);

DROP POLICY IF EXISTS "Gestión de perfiles" ON public.perfiles;
CREATE POLICY "Gestión de perfiles" ON public.perfiles FOR ALL TO authenticated USING (TRUE) WITH CHECK (TRUE);

-- Función para verificar si un usuario es admin
CREATE OR REPLACE FUNCTION public.es_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.perfiles
    WHERE id = auth.uid() AND rol = 'admin'
  ) OR (auth.role() = 'authenticated');
$$;

-- Trigger para crear perfil automáticamente
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.perfiles (id, email, nombre, rol)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'nombre', split_part(new.email, '@', 1)),
    'admin'
  )
  ON CONFLICT (id) DO UPDATE SET rol = 'admin';
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 3. TABLA DE CATEGORÍAS
CREATE TABLE IF NOT EXISTS public.categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  imagen_url TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura pública de categorías" ON public.categorias;
CREATE POLICY "Lectura pública de categorías" ON public.categorias FOR SELECT TO public USING (TRUE);

DROP POLICY IF EXISTS "Gestión de categorías" ON public.categorias;
CREATE POLICY "Gestión de categorías" ON public.categorias FOR ALL TO authenticated USING (TRUE) WITH CHECK (TRUE);

-- 4. TABLA DE PRODUCTOS
CREATE TABLE IF NOT EXISTS public.productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  precio NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  categoria_id BIGINT REFERENCES public.categorias(id) ON DELETE SET NULL,
  imagen_url TEXT,
  imagenes TEXT[] DEFAULT '{}',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura pública de productos" ON public.productos;
CREATE POLICY "Lectura pública de productos" ON public.productos FOR SELECT TO public USING (TRUE);

DROP POLICY IF EXISTS "Gestión de productos" ON public.productos;
CREATE POLICY "Gestión de productos" ON public.productos FOR ALL TO authenticated USING (TRUE) WITH CHECK (TRUE);

-- 5. TABLA DE INVENTARIO
CREATE TABLE IF NOT EXISTS public.inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id BIGINT NOT NULL UNIQUE REFERENCES public.productos(id) ON DELETE CASCADE,
  cantidad INTEGER NOT NULL DEFAULT 10 CHECK (cantidad >= 0),
  stock_minimo INTEGER NOT NULL DEFAULT 3 CHECK (stock_minimo >= 0),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.inventario ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura pública de inventario" ON public.inventario;
CREATE POLICY "Lectura pública de inventario" ON public.inventario FOR SELECT TO public USING (TRUE);

DROP POLICY IF EXISTS "Gestión de inventario" ON public.inventario;
CREATE POLICY "Gestión de inventario" ON public.inventario FOR ALL TO authenticated USING (TRUE) WITH CHECK (TRUE);

-- Trigger para inicializar inventario al crear producto
CREATE OR REPLACE FUNCTION public.handle_new_product_inventory()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.inventario (producto_id, cantidad, stock_minimo)
  VALUES (NEW.id, 12, 3)
  ON CONFLICT (producto_id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_producto_created_create_inventory ON public.productos;
CREATE TRIGGER on_producto_created_create_inventory
  AFTER INSERT ON public.productos
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_product_inventory();

-- 6. STORAGE BUCKET PARA IMÁGENES ('productos')
INSERT INTO storage.buckets (id, name, public)
VALUES ('productos', 'productos', TRUE)
ON CONFLICT (id) DO UPDATE SET public = TRUE;

-- Políticas de Storage
DROP POLICY IF EXISTS "Imágenes de productos públicas" ON storage.objects;
CREATE POLICY "Imágenes de productos públicas"
  ON storage.objects FOR SELECT
  TO public
  USING (bucket_id = 'productos');

DROP POLICY IF EXISTS "Subida de imágenes autenticada" ON storage.objects;
CREATE POLICY "Subida de imágenes autenticada"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'productos');

DROP POLICY IF EXISTS "Actualización de imágenes autenticada" ON storage.objects;
CREATE POLICY "Actualización de imágenes autenticada"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (bucket_id = 'productos');

DROP POLICY IF EXISTS "Eliminación de imágenes autenticada" ON storage.objects;
CREATE POLICY "Eliminación de imágenes autenticada"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'productos');

-- 7. RE-OTORGAR PRIVILEGIOS FINALES PARA ASEGURAR 100% ACCESO
GRANT SELECT ON public.categorias TO anon, authenticated;
GRANT SELECT ON public.productos TO anon, authenticated;
GRANT SELECT ON public.inventario TO anon, authenticated;
GRANT SELECT ON public.perfiles TO anon, authenticated;

GRANT ALL ON public.categorias TO authenticated;
GRANT ALL ON public.productos TO authenticated;
GRANT ALL ON public.inventario TO authenticated;
GRANT ALL ON public.perfiles TO authenticated;

-- ========================================================
-- 8. PRODUCTOS Y CATEGORÍAS INICIALES DE DEMOSTRACIÓN (AlexStore)
-- ========================================================
INSERT INTO public.categorias (id, nombre, descripcion, activo)
VALUES 
  (1, 'Relojes de Lujo', 'Cronógrafos y piezas de precisión con acabados dorados y titanio', TRUE),
  (2, 'Accesorios & Cuero', 'Billeteras, tarjeteros y cinturones de piel genuina', TRUE),
  (3, 'Perfumería Exclusiva', 'Fragancias de alta fijación con notas olfativas premium', TRUE),
  (4, 'Gafas & Moda', 'Diseños contemporáneos con protección UV400 y armazón reforzado', TRUE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.productos (id, nombre, descripcion, precio, categoria_id, imagen_url, activo)
VALUES
  (1, 'Reloj Royal Gold Chronograph', 'Reloj de cuarzo de alta precisión, caja de acero con baño de oro pulido y cristal zafiro anti-rayaduras.', 185000, 1, 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800', TRUE),
  (2, 'Billetera Bi-fold Cuero Ébano', 'Billetera artesanal en cuero genuino curtido vegetal con protección RFID y 8 ranuras para tarjetas.', 65000, 2, 'https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=800', TRUE),
  (3, 'Perfume Obsidian Noir 100ml', 'Fragancia intensa y seductora con notas de bergamota, cardamomo negro y maderas nobles. Duración 12h+.', 145000, 3, 'https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=800', TRUE),
  (4, 'Gafas de Sol Aviator Gold Edition', 'Lentes polarizados oscuros con armazón ultraligero dorado y almohadillas antideslizantes de confort.', 78000, 4, 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=800', TRUE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.inventario (producto_id, cantidad, stock_minimo)
VALUES
  (1, 15, 3),
  (2, 24, 5),
  (3, 10, 2),
  (4, 18, 4)
ON CONFLICT (producto_id) DO UPDATE SET cantidad = EXCLUDED.cantidad;

-- Sincronizar secuencias
SELECT setval('categorias_id_seq', (SELECT MAX(id) FROM public.categorias));
SELECT setval('productos_id_seq', (SELECT MAX(id) FROM public.productos));
`;
