-- ========================================================
-- CATÁLOGO DIGITAL SUPABASE - SCRIPT SQL COMPLETO
-- Ejecuta este script en el SQL Editor de tu proyecto Supabase
-- ========================================================

-- 1. Tabla de Perfiles (para roles de usuario, en particular 'admin')
CREATE TABLE IF NOT EXISTS public.perfiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  nombre TEXT,
  rol TEXT NOT NULL DEFAULT 'user', -- 'admin' o 'user'
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Habilitar RLS en perfiles
ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;

-- Función de conveniencia para verificar si el usuario actual es admin
CREATE OR REPLACE FUNCTION public.es_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.perfiles
    WHERE id = auth.uid() AND rol = 'admin'
  );
$$;

-- Políticas de perfiles:
-- Cualquier usuario autenticado puede leer su propio perfil; admins pueden leer todos los perfiles
CREATE POLICY "Lectura de perfiles propios o admins"
  ON public.perfiles FOR SELECT
  TO authenticated
  USING (id = auth.uid() OR public.es_admin());

-- Solo admins o el propio usuario pueden actualizar su perfil
CREATE POLICY "Actualizar perfil propio o admin"
  ON public.perfiles FOR UPDATE
  TO authenticated
  USING (id = auth.uid() OR public.es_admin())
  WITH CHECK (id = auth.uid() OR public.es_admin());

-- Trigger para crear perfil automáticamente al registrarse usuario en auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.perfiles (id, email, nombre, rol)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'nombre', split_part(new.email, '@', 1)),
    COALESCE(new.raw_user_meta_data->>'rol', 'user')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 2. Tabla de Categorías
CREATE TABLE IF NOT EXISTS public.categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  imagen_url TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;

-- Lectura pública para categorías activas (el catálogo es público)
CREATE POLICY "Lectura pública de categorías activas"
  ON public.categorias FOR SELECT
  TO public
  USING (activo = TRUE OR public.es_admin());

-- Modificación solo para administradores
CREATE POLICY "Admins gestionan categorias"
  ON public.categorias FOR ALL
  TO authenticated
  USING (public.es_admin())
  WITH CHECK (public.es_admin());


-- 3. Tabla de Productos
CREATE TABLE IF NOT EXISTS public.productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  precio NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  categoria_id BIGINT REFERENCES public.categorias(id) ON DELETE SET NULL,
  imagen_url TEXT,
  imagenes TEXT[] DEFAULT '{}',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;

-- Lectura pública para productos activos
CREATE POLICY "Lectura pública de productos activos"
  ON public.productos FOR SELECT
  TO public
  USING (activo = TRUE OR public.es_admin());

-- Solo admins pueden insertar, actualizar o eliminar productos
CREATE POLICY "Admins gestionan productos"
  ON public.productos FOR ALL
  TO authenticated
  USING (public.es_admin())
  WITH CHECK (public.es_admin());


-- 4. Tabla de Inventario
CREATE TABLE IF NOT EXISTS public.inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id BIGINT NOT NULL UNIQUE REFERENCES public.productos(id) ON DELETE CASCADE,
  cantidad INTEGER NOT NULL DEFAULT 0 CHECK (cantidad >= 0),
  stock_minimo INTEGER NOT NULL DEFAULT 5 CHECK (stock_minimo >= 0),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.inventario ENABLE ROW LEVEL SECURITY;

-- Lectura pública del inventario (para mostrar disponibilidad en el catálogo)
CREATE POLICY "Lectura pública de inventario"
  ON public.inventario FOR SELECT
  TO public
  USING (TRUE);

-- Solo administradores pueden modificar el inventario
CREATE POLICY "Admins gestionan inventario"
  ON public.inventario FOR ALL
  TO authenticated
  USING (public.es_admin())
  WITH CHECK (public.es_admin());

-- Trigger para crear registro en inventario automáticamente cuando se crea un producto
CREATE OR REPLACE FUNCTION public.handle_new_product_inventory()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.inventario (producto_id, cantidad, stock_minimo)
  VALUES (NEW.id, 10, 3)
  ON CONFLICT (producto_id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_producto_created_create_inventory ON public.productos;
CREATE TRIGGER on_producto_created_create_inventory
  AFTER INSERT ON public.productos
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_product_inventory();


-- 5. Bucket de Supabase Storage: 'productos'
-- Inserta el bucket 'productos' si no existe
INSERT INTO storage.buckets (id, name, public)
VALUES ('productos', 'productos', TRUE)
ON CONFLICT (id) DO UPDATE SET public = TRUE;

-- Políticas de Storage para el bucket 'productos'
-- 5.1 Lectura pública de imágenes
CREATE POLICY "Imágenes de productos públicas"
  ON storage.objects FOR SELECT
  TO public
  USING (bucket_id = 'productos');

-- 5.2 Subida y gestión de imágenes solo para admins autenticados
CREATE POLICY "Admins pueden subir imágenes a productos"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'productos' AND public.es_admin());

CREATE POLICY "Admins pueden actualizar imágenes en productos"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (bucket_id = 'productos' AND public.es_admin());

CREATE POLICY "Admins pueden eliminar imágenes en productos"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'productos' AND public.es_admin());

-- ========================================================
-- INSTRUCCIÓN PARA ASIGNAR ROL DE ADMINISTRADOR
-- Ejecuta esto reemplazando el correo con el correo del admin registrado:
-- UPDATE public.perfiles SET rol = 'admin' WHERE email = 'tu_correo@ejemplo.com';
-- ========================================================
